### ISSUE TITLE
orangescrum is not working

### ISSUE THREAD

**Issue by alex700900** [Orangescrum/orangescrum#100]
I tied to install, I follow the tutorial with everything and I didn't have any error, but when I go to the browser and put localhost and the page It's blank 

It's not showing nothing

any advise??

**Comment by alex700900** [comment]
this error 
[Fri Sep 04 10:21:50 2015] [notice] Apache/2.2.15 (Unix) DAV/2 PHP/5.3.3 configured -- resuming normal operations
[Fri Sep 04 10:21:50 2015] [error] avahi_entry_group_add_service_strlst("localhost") failed: Invalid host name
[Fri Sep 04 10:21:59 2015] [error] [client ::1] PHP Warning:  _cake_core_ cache was unable to write 'cake_dev_es-es' to File cache in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php on line 325
[Fri Sep 04 10:21:59 2015] [error] [client ::1] PHP Warning:  /var/www/html/orangescrumPM/app/tmp/cache/persistent/ is not writable in /var/www/html/orangescrumPM/lib/Cake/Cache/Engine/FileEngine.php on line 384
[Fri Sep 04 10:21:59 2015] [error] [client ::1] PHP Fatal error:  Uncaught exception 'CacheException' with message 'Cache engine _cake_core_ is not properly configured.' in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php:181\nStack trace:\n#0 /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')\n#1 /var/www/html/orangescrumPM/app/Config/core.php(292): Cache::config('_cake_core_', Array)\n#2 /var/www/html/orangescrumPM/lib/Cake/Core/Configure.php(72): include('/var/www/html/o...')\n#3 /var/www/html/orangescrumPM/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)\n#4 /var/www/html/orangescrumPM/app/webroot/index.php(77): include('/var/www/html/o...')\n#5 {main}\n  thrown in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php on line 181
[Fri Sep 04 10:22:18 2015] [error] [client ::1] PHP Warning:  _cake_core_ cache was unable to write 'cake_dev_es-es' to File cache in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php on line 325
[Fri Sep 04 10:22:18 2015] [error] [client ::1] PHP Warning:  /var/www/html/orangescrumPM/app/tmp/cache/persistent/ is not writable in /var/www/html/orangescrumPM/lib/Cake/Cache/Engine/FileEngine.php on line 384
[Fri Sep 04 10:22:18 2015] [error] [client ::1] PHP Fatal error:  Uncaught exception 'CacheException' with message 'Cache engine _cake_core_ is not properly configured.' in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php:181\nStack trace:\n#0 /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')\n#1 /var/www/html/orangescrumPM/app/Config/core.php(292): Cache::config('_cake_core_', Array)\n#2 /var/www/html/orangescrumPM/lib/Cake/Core/Configure.php(72): include('/var/www/html/o...')\n#3 /var/www/html/orangescrumPM/lib/Cake/bootstrap.php(175): Configure::bootstrap(true)\n#4 /var/www/html/orangescrumPM/app/webroot/index.php(77): include('/var/www/html/o...')\n#5 {main}\n  thrown in /var/www/html/orangescrumPM/lib/Cake/Cache/Cache.php on line 181

**Comment by alex700900** [comment]
![image](https://cloud.githubusercontent.com/assets/14126868/9691946/92a9d50a-52fa-11e5-95de-7d25224fd0a2.png)

it's has the permission, and I'm using a Centos 6
well I use the tutorial http://www.orangescrum.org/how-to-install-orangescrum-on-centos
and It's has many changes with the tutorial 
http://www.orangescrum.org/general-installation-guide

in some points.. It's no very clear... I'm make the virtualhost like this and nothing.
![capture](https://cloud.githubusercontent.com/assets/14126868/9692038/40bea490-52fb-11e5-917e-82055495c004.JPG)

**Comment by 2yscw** [comment]
Have you solved the problem?I also appeared the same problem.

**Comment by pabloveintimilla** [comment]
Have you solved the problem?I also appeared the same problem.
