### ISSUE TITLE
Error: Can't connect to MySQL

### ISSUE THREAD

**Issue by Rage20rage** [Orangescrum/orangescrum#203]
Hey,
i can't use the Programm, because i have an error, which i can't explain myself.

The Website Output:
`Please check you database connection in `app/Config/database.php` or may be some syntax error in your code`

The Log from app/tmp/logs/error.log:
```
2019-02-18 12:24:54 Error: Fatal Error (64): Cannot use 'String' as class name as it is reserved in [/var/www/html/todo/lib/Cake/Utility/String.php, line 25]
2019-02-18 12:24:54 Error: [InternalErrorException] Internal Server Error
Request URL: /todo/
Stack Trace:
#0 /var/www/html/todo/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(64, 'Cannot use 'Str...', '/var/www/html/t...', 25)
#1 /var/www/html/todo/lib/Cake/Core/App.php(929): ErrorHandler::handleError(64, 'Cannot use 'Str...', '/var/www/html/t...', 25, Array)
#2 /var/www/html/todo/lib/Cake/Core/App.php(902): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```

The app/Config/database.php:
```
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'orangescrum',
                'password' => 'secret',
                'database' => 'orangescrum',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}
```

I hope somebody can help me.
Thank you,
Marko

**Comment by Rage20rage** [comment]
PS: I had checked all variables, they are right.

**Comment by Dimitrah** [comment]
Can you try 
sudo mysql -u orangescrumuser -p orangescrum < database.sql
and see if there is any problem with this?

**Comment by Rage20rage** [comment]
This works. I don't know what the Problem was, but i fixed it with a reinstall of my Debian Server.
