### ISSUE TITLE
[MissingTableException] Table addons for model Addon was not found in datasource default.

### ISSUE THREAD

**Issue by choungchamnab** [Orangescrum/orangescrum#208]
I got this error When try to install
`2019-05-08 08:36:23 Error: [MissingTableException] Table addons for model Addon was not found in datasource default.
Exception Attributes: array (
  'table' => 'addons',
  'class' => 'Addon',
  'ds' => 'default',
)
Request URL: /oc/
Stack Trace:
#0 /Applications/MAMP/htdocs/oc/lib/Cake/Model/Model.php(3667): Model->setSource('addons')
#1 /Applications/MAMP/htdocs/oc/lib/Cake/Model/Model.php(3038): Model->getDataSource()
#2 /Applications/MAMP/htdocs/oc/lib/Cake/Model/Model.php(3010): Model->_readDataSource('first', Array)
#3 /Applications/MAMP/htdocs/oc/app/Model/AppModel.php(35): Model->find('first', Array)
#4 /Applications/MAMP/htdocs/oc/app/Controller/AppController.php(1158): AppModel->find('first', Array)
#5 /Applications/MAMP/htdocs/oc/app/Controller/AppController.php(90): AppController->is_AddonInstalled('PHPMAILER')
#6 /Applications/MAMP/htdocs/oc/app/Controller/UsersController.php(45): AppController->beforeFilter()
#7 /Applications/MAMP/htdocs/oc/lib/Cake/Event/CakeEventManager.php(243): UsersController->beforeFilter(Object(CakeEvent))
#8 /Applications/MAMP/htdocs/oc/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))
#9 /Applications/MAMP/htdocs/oc/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#10 /Applications/MAMP/htdocs/oc/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#11 /Applications/MAMP/htdocs/oc/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}`

**Comment by orangescrum1** [comment]
Hi @Kendokai,

We have already fixed the issue. Could you please download the latest version of Orangescrum from [here](https://www.orangescrum.org/free-download/?refer=b&utm_expid=.YT_TN7HOQxGrE6yGowbULQ.1&utm_referrer=https%3A%2F%2Fwww.orangescrum.org%2F)

Thanks,
Orangescrum Team
