### ISSUE TITLE
Spinner spin round and round while Creating Task

### ISSUE THREAD

**Issue by corientdev** [Orangescrum/orangescrum#75]
Hi,

Spinner spin round and round while Creating Task

See the image its saving the task from last 20-25 Minutes

![2015-07-09 13_07_09-orangescrum](https://cloud.githubusercontent.com/assets/9655234/8590197/e6afdce4-263b-11e5-92a3-2adecf273f50.png)

**Comment by fbayer** [comment]
Is it a new installation or did anything happen (e.g. update, upgrade, changes within the code)?
Make sure the database settings are correct (app/Config/database.php) and the app has write access to the database.

**Comment by corientdev** [comment]
1. New Installation it is.

2. I don't think its SQL Error its working properly even task also gets added but it doesn't say Task added successfully or something it just get stuck at that spinner on Add Task page

**Comment by cruggieri** [comment]
+1 
In my fresh installation also occours:
- no way to open tasks: if I click in a task "loading" message appear but nothing happen
- In Dashboard "Summary", "Recent Activities", "Development", "Task Status" spinner spin round and round and nothing happen.

**Comment by Orangescrum** [comment]
Hi,
Please ensure that the Configure::write('debug',0); in the core.php.
If the value is not set as 0 then set it to 0.

**Comment by fbayer** [comment]
@Orangescrum But CakePHP's debug mode could be very useful to finding bugs (if someone extend the app).
If the spinner spins around all the time it seems like some AJAX calls do not complete properly?!

You could check this via your browser's developer tools (F12) and look up the XHR request and responses within the network tab.

**Comment by cruggieri** [comment]
I set debug to zero in app/Config/core.php and lib/Cake/Console/Templates/skel/Config/core.php, but nothing changes.

**Comment by corientdev** [comment]
`exception 'FatalErrorException' with message 'Call to a member function sendGridEmail() on a non-object' in /var/www/html/app/Lib/Error/AppExceptionRenderer.php:39 Stack trace: #0 /var/www/html/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/a...', 39) #1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/a...', 39, Array) #2 /var/www/html/lib/Cake/Core/App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/a...', 39, Array) #3 /var/www/html/lib/Cake/Core/App.php(902): App::_checkFatalError() #4 [internal function]: App::shutdown() #5 {main} `


`Fatal Error

Error: Call to a member function sendGridEmail() on a non-object
File: /var/www/html/app/Lib/Error/AppExceptionRenderer.php
Line: 39`

Error while posting data to `/easycases/ajaxpostcase`

**Comment by corientdev** [comment]
Does this helps @Orangescrum ?

**Comment by cruggieri** [comment]
Checked my error.log and I have the same error as @corientdev.

**Comment by corientdev** [comment]
Please suggest some fix anyone.. Error is not very clear..

**Comment by corientdev** [comment]
It works without error on my local windows pc

**Comment by Orangescrum** [comment]
Hi corientdev,
Can you please provide the detail of the environment where you are getting the issue?

**Comment by corientdev** [comment]
Ubuntu 14.04.2 LTS hosted @ AWS 1gb ram vps server

**Comment by corientdev** [comment]
I don't know but the latest build i picked up from master today have lots of errors. Want me to submit?

**Comment by cruggieri** [comment]
timelog always display "There is some Problem
Please check you database connection in `app/Config/database.php` or may be some syntax error in your code"

But the file is fine.

**Comment by nixwiek** [comment]
+1
In my fresh installation also occours:

    no way to open tasks: if I click in a task "loading" message appear but nothing happens
    In Dashboard: "Summary", "Recent Activities", "Development", "Task Status" spinner spin round and round and nothing happen.

The error ocures onely when a Umlaut äöüß is in the name of the project.
The database was created with "DEFAULT CHARACTER SET utf8"

**Comment by snguyen-vn** [comment]
I am dealing with exactly same problem. I've checkout latest master code, but it does not help.

Anyone happens to know what I should do?

**Comment by corientdev** [comment]
Linux Ubuntu 14.04 LTS

**Comment by drwest143** [comment]
I am having the same issue. All works fine, but the error persists. 

CentOS Linux release 7.1.1503 (Core)

**Comment by Prabhudas** [comment]
Hi,

Please download the latest version of Orangescrum.
We have fixed the issues.

**Comment by itzsashi** [comment]
Hi Prabhu,

we have downloaded the latest version and configured on CentOS 7, we have the same issue, task never end up and it wont saved.

**Comment by nixwiek** [comment]
Am 16.09.2015 um 06:35 schrieb itzsashi:
>
> Hi Prabhu,
>
> we have downloaded the latest version and configured on CentOS 7, we
> have the same issue, task never end up and it wont saved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Orangescrum/orangescrum/issues/75#issuecomment-140624704>.
>
same problem with new version.

If there is a

umlaut "äöü..."
utf-8:  &#246

in project Name.  Orangescrum crashes.

**Comment by cusumanodaniele** [comment]
Hi, same problem here with latest ver. I must refresh after 10  seconds to see the task saved..
Anyone fixed?

**Comment by alexcumpanici** [comment]
Any updates on this?

**Comment by corientdev** [comment]
I think owner is uninterested in solving bugs. He just want to be famous without working. He must be making some videos, uploading it on youtube  and bragging somewhere about the software which doesn't work.. Lol

**Comment by alexcumpanici** [comment]
I'm back. Orangescrum is working for us now. Finally.
For some reasons, is working when mysql strict mode is disabled. It seems that the website does not conform to all mysql standards thus gets blocked.

**Comment by bkrajendra** [comment]
This issue is not solved. Im using latest version but im still getting this error.
If explored in chrome developer mode i found it shows database error on Task detail Ajax request. while database connectivity is ok as ive already created project and tasks and also added users.

Is there anyone who is able to resolve this error.

**Comment by medivhok** [comment]
I have this error when I try to update my profile. I'm using lubuntu 16.04, fresh install.
The developer tools give me these errors (the trim appears when I want to update the changes) :
```
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
GET http://192.168.2.181/orangescrum/users/image_thumb/?type=photos&file=user.png&sizex=28&sizey=28&quality=100 500 (Internal Server Error)
Uncaught TypeError: Cannot read property 'trim' of undefined
```

**Comment by bkrajendra** [comment]
The are lot of issue in this script. Its difficult to find out exact cause.
Initially I was getting database error, while everything else was working fine, but getting database error while creating task or projects. Ive resolved it as there was issue with my date configuration. there were few records with different date config and i changed date config latter this might have created some issue in time difference calculation script and casing error. wish i could only see when i open the error log.

After this everything was working fine and one day I found it again started giving database connection error for creating new project and task. I think this might be related to email as other database related function like creating template and other are working fine.

**Comment by hitendra52** [comment]
Have anyone got it working ? In my case its saving to database but while submitting spinner spin round and round . 
The question : is it sending mails on task created or task updated ?  In my case its not sending mail , and i have doubt on that only. Its trying to send email and not going fine so it spins round and round.  This just a case i am thinking may causing issue .

**Comment by raakeshkumar** [comment]
I was able to install it successfully but when I try to login, it shows me following error:

`Error:` Uncaught Error: Call to a member function sendGridEmail() on null in /Library/WebServer/Documents/task_system/app/Lib/Error/AppExceptionRenderer.php:39 Stack trace: #0 /Library/WebServer/Documents/task_system/lib/Cake/Error/ExceptionRenderer.php(190): AppExceptionRenderer->pdoError(Object(PDOException)) #1 /Library/WebServer/Documents/task_system/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render() #2 [internal function]: ErrorHandler::handleException(Object(PDOException)) #3 {main} thrown	
File: /Library/WebServer/Documents/task_system/app/Lib/Error/AppExceptionRenderer.php	
Line: 39

**Comment by thaidv8x** [comment]
i waste a day with this problem. I use centos 7 with php 7.2, maria db 5.5 and apache.
But when i use centos 7, php 5.6 mariadb 5.5, this problem solved.
Loading at Task section down show anymore...
