### ISSUE TITLE
View of tasks is not displayed

### ISSUE THREAD

**Issue by globalthinking321** [Orangescrum/orangescrum#9]
After the installation everything works fine so far. Only the tasks page is not displayed and hangs.
What is the reason for this
![Bildschirmfoto 2022-06-15 um 10 00 47](https://user-images.githubusercontent.com/107540139/173774817-55355460-90f5-47bb-b9f4-53ff5cbc665d.png)
?

**Comment by amitanirudha** [comment]
@globalthinking321 @solka2050 - Can you please share the below details? 

1. PHP version
2. MySQL version
3. Error log file inside (app/tmp/logs)
4. Browser console error
5. Hosting environment (Ubuntu/Linux/Shared hosting/Localhost)

Once you share the above details, we will look into this and help you to install the community edition.

**Comment by solka2050** [comment]
Console Error: 

Expression
not available
Expression
not available
﻿
exporting.js:22 Uncaught ReferenceError: Highcharts is not defined
    at exporting.js:22:458
VM188:3 Uncaught ReferenceError: GrpBy is not defined
    at eval (eval at tmpl (os_core.js?v=36:1:151), <anonymous>:3:457)
    at tmpl (os_core.js?v=36:1:482)
    at Object.success (dashboard_v1.js?v=36:548:41)
    at c (jquery-1.10.1.min.js:4:26051)
    at Object.fireWith [as resolveWith] (jquery-1.10.1.min.js:4:26856)
    at k (jquery-1.10.1.min.js:6:14236)
    at XMLHttpRequest.r (jquery-1.10.1.min.js:6:18624)


Web server
cpsrvd 11.104.0.5
Database client version: libmysql - mysqlnd 7.4.30
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.4.30

Database server
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.35-MariaDB - MariaDB Server

phpMyAdmin
Version information: 4.9.7

Hosting Centos - 7




![Capture](https://user-images.githubusercontent.com/10573068/178233320-9f51bf68-f787-4c4d-b911-3e4e1e3fcd83.JPG)

**Comment by amitanirudha** [comment]
@solka2050 Hi Sudhir, thank you for sharing the details. 

Can you please downgrade your PHP version to 7.2 from 7.4.30? Also, kindly check if your MySQL strict mode is turned OFF or ON. If it is ON, then make sure it is turned OFF. 

Let us know if that works for you. 

Thanks,
Amit

**Comment by solka2050** [comment]
> @solka2050 Hi Sudhir, thank you for sharing the details.
> 
> Can you please downgrade your PHP version to 7.2 from 7.4.30? Also, kindly check if your MySQL strict mode is turned OFF or ON. If it is ON, then make sure it is turned OFF.
> 
> Let us know if that works for you.
> 
> Thanks, Amit

What happen @amitanirudha is there any solution

**Comment by dklane** [comment]
My webhost, Dreamhost, does not support PHP that is older than 7.4. It also does not offer MySQL strict mode. I observed the task display concern with releases 2.0.1 - 2.0.8. Do you have any workarounds?

**Comment by woodb01** [comment]
Current provider does not support PHP 7.2 for security and performance reasons. Lowest I can go is 7.3 but have other sites all running 7.4. Since the other sites are business sites, and the provider does not offer 7.2, is my only option to abandon Orangescrum?

**Comment by valdomagana** [comment]
Does anyone have the solution?

**Comment by Anil-Chaudhary-netclues** [comment]
Hello Orangescrum,

Any Update on this.

I am facing same issue.
My PHP version is 7.2
and Mysql Version is 5.7

can you please let me know what is the exact issue for this.
Note: i have setup them on localhost and that working fine. why they is not working on server. can you please let me know.

**URGENT**: Need your Quick Help,
